"""
agents/dispute_resolver/schemas.py

Pydantic schemas to validate data inputs and outputs for the Dispute & Escalation Resolver Agent (Agent 7 of 7).
"""

from typing import Any
from pydantic import BaseModel, Field


class DisputeResolverOutput(BaseModel):
    """Standardised output payload for the Dispute & Escalation Resolver Agent."""

    dispute_id: str = Field(..., description="Unique dispute transaction ID")
    booking_id: str = Field(..., description="Target booking ID associated with the dispute")
    dispute_type: str = Field(..., description="Dispute category classification")
    classified_severity: str = Field(..., description="Severity level: low, medium, high, critical")
    resolution_path: str = Field(..., description="Standardised path used to resolve this category")
    action_taken: str = Field(..., description="Description of resolution action taken")
    refund_amount_pkr: int = Field(..., description="Total refund calculated in PKR")
    compensation_pkr: int = Field(..., description="Total compensation credited in PKR")
    provider_consequence: str = Field(..., description="Description of warning/penalty consequence applied to the provider")
    blacklist_flagged: bool = Field(..., description="True if provider is blacklisted (3rd dispute reached)")
    human_escalation_required: bool = Field(..., description="True if customer support agent must intervene")
    resolution_message: str = Field(..., description="Warm, friendly, localized resolution message generated by LLM")
    dispute_log: list[str] = Field(..., description="Step-by-step transaction logs")
