from datetime import datetime, timezone
from typing import List
from .provider import Provider, Location
from .user import User
from .booking import Booking, BookingStatus, PriceBreakdown
from .dispute import Dispute, DisputeStatus

# --- MOCK PROVIDERS (30 Realistic Pakistani Providers) ---
MOCK_PROVIDERS: List[Provider] = [
    Provider(
        id="prov_001",
        name="Hassan Ustad",
        service_type="Plumber",
        location=Location(lat=31.5207, lng=74.3702),
        address="Random area, Lahore",
        rating=4.3,
        on_time_score=80.6,
        cancellation_rate=9.8,
        base_rate=1403.0,
        availability=True,
        skills=['Leak Repair', 'Motor Installation']
    ),
    Provider(
        id="prov_002",
        name="Bhatti Electrician",
        service_type="Plumber",
        location=Location(lat=33.7124, lng=73.0059),
        address="Random area, Islamabad",
        rating=4.6,
        on_time_score=98.1,
        cancellation_rate=5.3,
        base_rate=1432.0,
        availability=True,
        skills=['Motor Installation', 'Geyser Repair']
    ),
    Provider(
        id="prov_003",
        name="Raza Works",
        service_type="Plumber",
        location=Location(lat=31.5284, lng=74.3576),
        address="Random area, Lahore",
        rating=3.6,
        on_time_score=99.1,
        cancellation_rate=3.9,
        base_rate=2180.0,
        availability=True,
        skills=['Geyser Repair', 'Motor Installation']
    ),
    Provider(
        id="prov_004",
        name="Waqas Services",
        service_type="Plumber",
        location=Location(lat=33.6575, lng=73.0539),
        address="Random area, Islamabad",
        rating=4.1,
        on_time_score=90.8,
        cancellation_rate=3.1,
        base_rate=2094.0,
        availability=False,
        skills=['Pipe Fitting', 'Geyser Repair']
    ),
    Provider(
        id="prov_005",
        name="Asif Mechanic",
        service_type="Plumber",
        location=Location(lat=31.4194, lng=73.1006),
        address="Random area, Faisalabad",
        rating=4.3,
        on_time_score=90.6,
        cancellation_rate=9.6,
        base_rate=2157.0,
        availability=True,
        skills=['Leak Repair', 'Motor Installation']
    ),
    Provider(
        id="prov_006",
        name="Zain Electrician",
        service_type="Plumber",
        location=Location(lat=31.5149, lng=74.3459),
        address="Random area, Lahore",
        rating=3.7,
        on_time_score=86.1,
        cancellation_rate=9.1,
        base_rate=2325.0,
        availability=True,
        skills=['Geyser Repair', 'Pipe Fitting']
    ),
    Provider(
        id="prov_007",
        name="Asif Pros",
        service_type="Plumber",
        location=Location(lat=31.3957, lng=73.1356),
        address="Random area, Faisalabad",
        rating=3.6,
        on_time_score=86.1,
        cancellation_rate=5.4,
        base_rate=1587.0,
        availability=True,
        skills=['Geyser Repair', 'Motor Installation']
    ),
    Provider(
        id="prov_008",
        name="Kamran Works",
        service_type="Plumber",
        location=Location(lat=24.8678, lng=67.0274),
        address="Random area, Karachi",
        rating=4.3,
        on_time_score=86.6,
        cancellation_rate=7.2,
        base_rate=1433.0,
        availability=False,
        skills=['Geyser Repair', 'Pipe Fitting']
    ),
    Provider(
        id="prov_009",
        name="Rizwan Mechanic",
        service_type="Plumber",
        location=Location(lat=33.6942, lng=73.0308),
        address="Random area, Islamabad",
        rating=3.8,
        on_time_score=94.0,
        cancellation_rate=3.6,
        base_rate=790.0,
        availability=True,
        skills=['Motor Installation', 'Leak Repair']
    ),
    Provider(
        id="prov_010",
        name="Naseem Tech",
        service_type="Plumber",
        location=Location(lat=33.5639, lng=73.0406),
        address="Random area, Rawalpindi",
        rating=4.0,
        on_time_score=84.7,
        cancellation_rate=4.4,
        base_rate=1639.0,
        availability=True,
        skills=['Motor Installation', 'Leak Repair']
    ),
    Provider(
        id="prov_011",
        name="Hassan Works",
        service_type="Electrician",
        location=Location(lat=33.5916, lng=73.0040),
        address="Random area, Rawalpindi",
        rating=5.0,
        on_time_score=91.7,
        cancellation_rate=9.5,
        base_rate=1442.0,
        availability=False,
        skills=['UPS Setup', 'Switchboard Repair']
    ),
    Provider(
        id="prov_012",
        name="Hassan Mechanic",
        service_type="Electrician",
        location=Location(lat=31.5036, lng=74.3529),
        address="Random area, Lahore",
        rating=4.9,
        on_time_score=97.0,
        cancellation_rate=4.5,
        base_rate=2440.0,
        availability=True,
        skills=['UPS Setup', 'Wiring']
    ),
    Provider(
        id="prov_013",
        name="Arif Pros",
        service_type="Electrician",
        location=Location(lat=33.7131, lng=73.0251),
        address="Random area, Islamabad",
        rating=3.5,
        on_time_score=85.4,
        cancellation_rate=4.5,
        base_rate=1918.0,
        availability=False,
        skills=['Wiring', 'UPS Setup']
    ),
    Provider(
        id="prov_014",
        name="Hassan Plumber",
        service_type="Electrician",
        location=Location(lat=24.8508, lng=66.9950),
        address="Random area, Karachi",
        rating=4.0,
        on_time_score=98.0,
        cancellation_rate=5.5,
        base_rate=1510.0,
        availability=True,
        skills=['Wiring', 'Solar Installation']
    ),
    Provider(
        id="prov_015",
        name="Zain Electrician",
        service_type="Electrician",
        location=Location(lat=33.7064, lng=73.0736),
        address="Random area, Islamabad",
        rating=4.3,
        on_time_score=96.5,
        cancellation_rate=6.0,
        base_rate=967.0,
        availability=True,
        skills=['UPS Setup', 'Wiring']
    ),
    Provider(
        id="prov_016",
        name="Naseem Bhai",
        service_type="Electrician",
        location=Location(lat=24.8391, lng=67.0453),
        address="Random area, Karachi",
        rating=4.7,
        on_time_score=86.6,
        cancellation_rate=1.7,
        base_rate=549.0,
        availability=True,
        skills=['Wiring', 'Switchboard Repair']
    ),
    Provider(
        id="prov_017",
        name="Tariq Ustad",
        service_type="Electrician",
        location=Location(lat=24.8981, lng=66.9640),
        address="Random area, Karachi",
        rating=4.6,
        on_time_score=86.2,
        cancellation_rate=0.8,
        base_rate=2271.0,
        availability=True,
        skills=['UPS Setup', 'Wiring']
    ),
    Provider(
        id="prov_018",
        name="Waqas Mechanic",
        service_type="Electrician",
        location=Location(lat=31.5065, lng=74.3529),
        address="Random area, Lahore",
        rating=3.5,
        on_time_score=84.0,
        cancellation_rate=4.9,
        base_rate=1682.0,
        availability=True,
        skills=['Wiring', 'Solar Installation']
    ),
    Provider(
        id="prov_019",
        name="Zain Works",
        service_type="Electrician",
        location=Location(lat=31.4495, lng=73.0496),
        address="Random area, Faisalabad",
        rating=4.6,
        on_time_score=84.7,
        cancellation_rate=0.5,
        base_rate=1130.0,
        availability=True,
        skills=['Wiring', 'UPS Setup']
    ),
    Provider(
        id="prov_020",
        name="Raza Works",
        service_type="Electrician",
        location=Location(lat=33.5540, lng=73.0228),
        address="Random area, Rawalpindi",
        rating=4.2,
        on_time_score=95.8,
        cancellation_rate=2.6,
        base_rate=930.0,
        availability=False,
        skills=['UPS Setup', 'Switchboard Repair']
    ),
    Provider(
        id="prov_021",
        name="Bilal Bhai",
        service_type="AC Technician",
        location=Location(lat=33.6996, lng=73.0425),
        address="Random area, Islamabad",
        rating=4.3,
        on_time_score=93.9,
        cancellation_rate=0.1,
        base_rate=2252.0,
        availability=True,
        skills=['Gas Refill', 'Installation']
    ),
    Provider(
        id="prov_022",
        name="Rizwan Ustad",
        service_type="AC Technician",
        location=Location(lat=33.6201, lng=73.0461),
        address="Random area, Rawalpindi",
        rating=4.2,
        on_time_score=82.8,
        cancellation_rate=1.8,
        base_rate=1047.0,
        availability=True,
        skills=['Installation', 'Compressor Repair']
    ),
    Provider(
        id="prov_023",
        name="Bilal Services",
        service_type="AC Technician",
        location=Location(lat=31.5467, lng=74.3941),
        address="Random area, Lahore",
        rating=4.9,
        on_time_score=100.0,
        cancellation_rate=0.6,
        base_rate=944.0,
        availability=True,
        skills=['Installation', 'Gas Refill']
    ),
    Provider(
        id="prov_024",
        name="Bilal Plumber",
        service_type="AC Technician",
        location=Location(lat=31.3953, lng=73.0775),
        address="Random area, Faisalabad",
        rating=3.8,
        on_time_score=93.5,
        cancellation_rate=1.8,
        base_rate=955.0,
        availability=True,
        skills=['AC Servicing', 'Compressor Repair']
    ),
    Provider(
        id="prov_025",
        name="Kamran Tech",
        service_type="AC Technician",
        location=Location(lat=33.6299, lng=73.0587),
        address="Random area, Rawalpindi",
        rating=3.6,
        on_time_score=96.2,
        cancellation_rate=2.6,
        base_rate=1991.0,
        availability=True,
        skills=['Compressor Repair', 'AC Servicing']
    ),
    Provider(
        id="prov_026",
        name="Bilal Electrician",
        service_type="AC Technician",
        location=Location(lat=24.9091, lng=67.0090),
        address="Random area, Karachi",
        rating=4.2,
        on_time_score=98.1,
        cancellation_rate=8.5,
        base_rate=666.0,
        availability=True,
        skills=['Installation', 'Gas Refill']
    ),
    Provider(
        id="prov_027",
        name="Rizwan Ustad",
        service_type="AC Technician",
        location=Location(lat=24.8965, lng=66.9840),
        address="Random area, Karachi",
        rating=4.7,
        on_time_score=98.9,
        cancellation_rate=5.8,
        base_rate=2082.0,
        availability=True,
        skills=['Gas Refill', 'AC Servicing']
    ),
    Provider(
        id="prov_028",
        name="Tariq Ustad",
        service_type="AC Technician",
        location=Location(lat=31.3628, lng=73.0809),
        address="Random area, Faisalabad",
        rating=4.6,
        on_time_score=86.0,
        cancellation_rate=0.8,
        base_rate=2271.0,
        availability=True,
        skills=['Installation', 'AC Servicing']
    ),
    Provider(
        id="prov_029",
        name="Zain Plumber",
        service_type="AC Technician",
        location=Location(lat=24.8895, lng=67.0462),
        address="Random area, Karachi",
        rating=4.9,
        on_time_score=89.3,
        cancellation_rate=4.0,
        base_rate=1641.0,
        availability=True,
        skills=['Gas Refill', 'Installation']
    ),
    Provider(
        id="prov_030",
        name="Hassan Ustad",
        service_type="AC Technician",
        location=Location(lat=31.5417, lng=74.3581),
        address="Random area, Lahore",
        rating=4.4,
        on_time_score=97.8,
        cancellation_rate=6.3,
        base_rate=2150.0,
        availability=True,
        skills=['Gas Refill', 'AC Servicing']
    ),
    Provider(
        id="prov_031",
        name="Usman Plumber",
        service_type="Carpenter",
        location=Location(lat=31.3984, lng=73.1164),
        address="Random area, Faisalabad",
        rating=4.0,
        on_time_score=94.8,
        cancellation_rate=0.5,
        base_rate=725.0,
        availability=True,
        skills=['Wood Polish', 'Cabinets']
    ),
    Provider(
        id="prov_032",
        name="Chaudhry Services",
        service_type="Carpenter",
        location=Location(lat=31.3929, lng=73.1090),
        address="Random area, Faisalabad",
        rating=3.5,
        on_time_score=91.3,
        cancellation_rate=8.7,
        base_rate=2091.0,
        availability=True,
        skills=['Cabinets', 'Furniture Repair']
    ),
    Provider(
        id="prov_033",
        name="Asif Works",
        service_type="Carpenter",
        location=Location(lat=31.4022, lng=73.0894),
        address="Random area, Faisalabad",
        rating=3.8,
        on_time_score=97.3,
        cancellation_rate=2.4,
        base_rate=1263.0,
        availability=True,
        skills=['Cabinets', 'Wood Polish']
    ),
    Provider(
        id="prov_034",
        name="Tariq Ustad",
        service_type="Carpenter",
        location=Location(lat=33.5446, lng=73.0053),
        address="Random area, Rawalpindi",
        rating=3.7,
        on_time_score=88.9,
        cancellation_rate=8.6,
        base_rate=850.0,
        availability=True,
        skills=['Wood Polish', 'Furniture Repair']
    ),
    Provider(
        id="prov_035",
        name="Saqib Services",
        service_type="Carpenter",
        location=Location(lat=33.5858, lng=73.0193),
        address="Random area, Rawalpindi",
        rating=3.8,
        on_time_score=91.6,
        cancellation_rate=7.0,
        base_rate=1991.0,
        availability=True,
        skills=['Door Fitting', 'Cabinets']
    ),
    Provider(
        id="prov_036",
        name="Zain Tech",
        service_type="Carpenter",
        location=Location(lat=33.5629, lng=73.0502),
        address="Random area, Rawalpindi",
        rating=5.0,
        on_time_score=98.5,
        cancellation_rate=5.5,
        base_rate=1770.0,
        availability=True,
        skills=['Cabinets', 'Furniture Repair']
    ),
    Provider(
        id="prov_037",
        name="Faizan Plumber",
        service_type="Carpenter",
        location=Location(lat=33.6585, lng=73.0645),
        address="Random area, Islamabad",
        rating=4.0,
        on_time_score=82.6,
        cancellation_rate=5.6,
        base_rate=1129.0,
        availability=True,
        skills=['Wood Polish', 'Cabinets']
    ),
    Provider(
        id="prov_038",
        name="Muhammad Pros",
        service_type="Carpenter",
        location=Location(lat=33.7038, lng=73.0521),
        address="Random area, Islamabad",
        rating=4.1,
        on_time_score=90.4,
        cancellation_rate=8.9,
        base_rate=529.0,
        availability=False,
        skills=['Cabinets', 'Furniture Repair']
    ),
    Provider(
        id="prov_039",
        name="Waqas Mechanic",
        service_type="Carpenter",
        location=Location(lat=31.4302, lng=73.1105),
        address="Random area, Faisalabad",
        rating=3.7,
        on_time_score=92.1,
        cancellation_rate=7.3,
        base_rate=914.0,
        availability=True,
        skills=['Furniture Repair', 'Door Fitting']
    ),
    Provider(
        id="prov_040",
        name="Saqib Mechanic",
        service_type="Carpenter",
        location=Location(lat=31.4302, lng=73.0881),
        address="Random area, Faisalabad",
        rating=3.7,
        on_time_score=90.1,
        cancellation_rate=3.5,
        base_rate=1518.0,
        availability=False,
        skills=['Door Fitting', 'Wood Polish']
    ),
    Provider(
        id="prov_041",
        name="Bilal Services",
        service_type="Painter",
        location=Location(lat=31.4365, lng=73.1265),
        address="Random area, Faisalabad",
        rating=4.6,
        on_time_score=97.2,
        cancellation_rate=1.8,
        base_rate=827.0,
        availability=False,
        skills=['Wall Painting', 'Exterior Paint']
    ),
    Provider(
        id="prov_042",
        name="Raza Mechanic",
        service_type="Painter",
        location=Location(lat=24.8233, lng=66.9522),
        address="Random area, Karachi",
        rating=4.1,
        on_time_score=86.5,
        cancellation_rate=4.5,
        base_rate=2011.0,
        availability=True,
        skills=['Wall Painting', 'Distemper']
    ),
    Provider(
        id="prov_043",
        name="Bhatti Specialist",
        service_type="Painter",
        location=Location(lat=31.5130, lng=74.3421),
        address="Random area, Lahore",
        rating=4.2,
        on_time_score=95.8,
        cancellation_rate=1.9,
        base_rate=2085.0,
        availability=True,
        skills=['Distemper', 'Wall Painting']
    ),
    Provider(
        id="prov_044",
        name="Usman Electrician",
        service_type="Painter",
        location=Location(lat=24.9037, lng=66.9678),
        address="Random area, Karachi",
        rating=4.8,
        on_time_score=98.2,
        cancellation_rate=9.3,
        base_rate=2290.0,
        availability=False,
        skills=['Wall Painting', 'Texture Paint']
    ),
    Provider(
        id="prov_045",
        name="Saqib Services",
        service_type="Painter",
        location=Location(lat=24.8558, lng=66.9810),
        address="Random area, Karachi",
        rating=3.8,
        on_time_score=99.6,
        cancellation_rate=7.7,
        base_rate=1359.0,
        availability=True,
        skills=['Texture Paint', 'Distemper']
    ),
    Provider(
        id="prov_046",
        name="Kamran Tech",
        service_type="Painter",
        location=Location(lat=33.7130, lng=73.0599),
        address="Random area, Islamabad",
        rating=4.1,
        on_time_score=82.6,
        cancellation_rate=2.5,
        base_rate=1590.0,
        availability=True,
        skills=['Texture Paint', 'Distemper']
    ),
    Provider(
        id="prov_047",
        name="Usman Plumber",
        service_type="Painter",
        location=Location(lat=33.6440, lng=73.0346),
        address="Random area, Islamabad",
        rating=4.8,
        on_time_score=87.9,
        cancellation_rate=3.3,
        base_rate=1584.0,
        availability=True,
        skills=['Texture Paint', 'Distemper']
    ),
    Provider(
        id="prov_048",
        name="Imran Mechanic",
        service_type="Painter",
        location=Location(lat=31.3692, lng=73.1339),
        address="Random area, Faisalabad",
        rating=3.6,
        on_time_score=97.8,
        cancellation_rate=5.8,
        base_rate=1379.0,
        availability=True,
        skills=['Texture Paint', 'Wall Painting']
    ),
    Provider(
        id="prov_049",
        name="Chaudhry Works",
        service_type="Painter",
        location=Location(lat=33.6276, lng=73.0327),
        address="Random area, Rawalpindi",
        rating=4.1,
        on_time_score=90.1,
        cancellation_rate=8.7,
        base_rate=1685.0,
        availability=True,
        skills=['Wall Painting', 'Distemper']
    ),
    Provider(
        id="prov_050",
        name="Waqas Bhai",
        service_type="Painter",
        location=Location(lat=31.4198, lng=73.0550),
        address="Random area, Faisalabad",
        rating=3.7,
        on_time_score=92.4,
        cancellation_rate=0.8,
        base_rate=2045.0,
        availability=True,
        skills=['Exterior Paint', 'Distemper']
    ),
]

MOCK_USERS: List[User] = [
    User(id="user_01", phone="+923001234567", preferred_language="ur"),
    User(id="user_02", phone="+923339876543", preferred_language="en"),
    User(id="user_03", phone="+923451122334", preferred_language="ur"),
]

# --- MOCK BOOKINGS ---
MOCK_BOOKINGS: List[Booking] = [
    Booking(
        id="book_01",
        user_id="user_01",
        provider_id="prov_khi_01",
        service_type="Plumber",
        status=BookingStatus.COMPLETED,
        price_breakdown=PriceBreakdown(base_fare=800.0, taxes=40.0, total=840.0)
    ),
    Booking(
        id="book_02",
        user_id="user_02",
        provider_id="prov_lhr_03",
        service_type="Chef/Cook",
        status=BookingStatus.IN_PROGRESS,
        price_breakdown=PriceBreakdown(base_fare=1500.0, taxes=75.0, total=1575.0)
    ),
    Booking(
        id="book_03",
        user_id="user_03",
        provider_id="prov_isb_01",
        service_type="Electrician",
        status=BookingStatus.PENDING,
        price_breakdown=PriceBreakdown(base_fare=1500.0, taxes=75.0, total=1575.0)
    )
]

# --- MOCK DISPUTES ---
MOCK_DISPUTES: List[Dispute] = [
    Dispute(
        id="disp_01",
        booking_id="book_01",
        reason="Provider was 1 hour late and did not complete the job properly.",
        status=DisputeStatus.IN_REVIEW,
        resolution=None
    )
]
