from typing import Optional
from pydantic import BaseModel, Field


class CallingAgentInput(BaseModel):
    """Input parameters for Agent 8 — Emergency Calling Agent."""

    booking_id: str = Field(..., description="Unique booking ID")
    user_name: str = Field(..., description="Customer's name")
    user_location: str = Field(..., description="Customer's location")
    provider_name: str = Field(..., description="Assigned provider's name")
    provider_cnic: str = Field(..., description="Assigned provider's CNIC number")
    provider_mobile: str = Field(..., description="Assigned provider's mobile number")
    trusted_contact_name: str = Field(..., description="Name of the trusted contact to call")
    trusted_contact_number: str = Field(..., description="Phone number of the trusted contact")
    service_type: str = Field(..., description="Type of service booked")
    booking_time: str = Field(..., description="Timestamp of when the booking was created/scheduled")
    estimated_minutes: int = Field(..., description="Estimated duration of the service in minutes")
    minutes_exceeded: int = Field(..., description="Number of minutes exceeded since completion window")
    
    # Trigger checks (optional, fallback values used if not retrieved from Firestore)
    user_responded: bool = Field(False, description="Whether the user has responded to warnings")
    provider_responded: bool = Field(False, description="Whether the provider has responded to warnings")
    safety_mode: bool = Field(True, description="Whether safety mode is enabled")
    warning_at_time: Optional[str] = Field(None, description="ISO timestamp when the warning was scheduled/sent")
    current_time: Optional[str] = Field(None, description="Current simulated/real time ISO timestamp")


class CallingAgentOutput(BaseModel):
    """Output results of Agent 8 — Emergency Calling Agent."""

    call_id: str = Field(..., description="Generated call ID log reference")
    booking_id: str = Field(..., description="Associated booking ID")
    call_status: str = Field(..., description="Status of the automated call (e.g. initiated, completed)")
    trusted_contact_name: str = Field(..., description="Name of the trusted contact called")
    trusted_contact_number: str = Field(..., description="Phone number of the trusted contact called")
    call_transcript: str = Field(..., description="Urdu script transcript generated by Gemini")
    call_duration_seconds: int = Field(..., description="Simulated duration of the phone call")
    call_sid: str = Field(..., description="Generated call SID string")
    firestore_logged: bool = Field(..., description="Whether the call log was successfully written to Firestore")
    booking_updated: bool = Field(..., description="Whether the booking record was updated in Firestore")
    trigger_reason: str = Field(..., description="Explanation of why this call was triggered")
    minutes_exceeded: int = Field(..., description="Minutes exceeded at the time of call")
    next_action: str = Field(..., description="Next operational step: await_user_response, escalate_to_authorities, mark_resolved")
