"""
agents/booking_executor/schemas.py

Pydantic data models to enforce runtime type checking and schema conformity
for the Booking Executor Agent (Agent 5 of 7).
"""

from typing import Any, Optional
from pydantic import BaseModel, Field


class BookingExecutorOutput(BaseModel):
    """Output schema for the Booking Executor Agent."""

    booking_id: str = Field(..., description="Unique booking ID generated for this transaction")
    status: str = Field("confirmed", description="Current status of the booking")
    provider_assigned: str = Field(..., description="Name of the provider assigned to this booking")
    confirmed_slot: str = Field(..., description="Confirmed appointment date and time slot")
    total_pkr: int = Field(..., description="Total price of the booking in PKR")
    before_state: dict[str, Any] = Field(..., description="State of provider/slot availability BEFORE booking")
    after_state: dict[str, Any] = Field(..., description="State of provider/slot availability AFTER booking")
    firestore_written: bool = Field(..., description="True if writing to Firestore succeeded")
    notification_payload: dict[str, Any] = Field(..., description="Payload dict generated for FCM push notifications")
    receipt: dict[str, Any] = Field(..., description="Full receipt detail of the booking")
    reminder_scheduled_at: str = Field(..., description="ISO timestamp for when the 23-hour pre-visit reminder is scheduled")
    confirmation_message: str = Field(..., description="Warm, friendly, localized booking confirmation message generated by LLM")
    safety_mode: bool = Field(False, description="True if safety protocols are active")
    estimated_completion_time: Optional[str] = Field(None, description="ISO timestamp of estimated completion")
    warning_scheduled_at: Optional[str] = Field(None, description="ISO timestamp of safety warning dispatch")
    safety_contact_notified: bool = Field(False, description="True if safety contacts are simulated as notified")
